### ISSUE TITLE
IpeImage retry functionality not fully working with rasterio 0.36.0

### ISSUE THREAD

**Issue by pramukta** [DigitalGlobe/gbdxtools#157]
This is because we catch `rasterio.RasterioIOError` [here](https://github.com/DigitalGlobe/gbdxtools/blob/master/gbdxtools/ipe/interface.py#L66) which isn't present in rasterio 0.36.  That means that when we get errors back from IPE it throws the exception: `
AttributeError: 'module' object has no attribute 'RasterioIOError'` rather than retrying.  This may be for only is only for non `TypeError` exceptions, not fully sure yet.  (ie when things return a 200 but error in a different way like curl connection dropped with data left tor read, etc).
